export const filterOut = [
  [21, "Accordion"],
  [22, "Harmonica"],
  [24, "Acoustic Guitar (nylon)"],
  [26, "Electric Guitar (jazz)"],
  [28, "Electric Guitar (muted)"],
  [32, "Acoustic Bass"],
  [33, "Electric Bass (finger)"],
  [34, "Electric Bass (picked)"],
  [35, "Electric Bass (fretless)"],
  [36, "Slap Bass 1"],
  [37, "Slap Bass 2"],
  [38, "Synth Bass 1"],
  [40, "Violin"],
  [41, "Viola"],
  [42, "Cello"],
  [43, "Contrabass"],
  [48, "String Ensemble 1 (often in marcato)"],
  [50, "Synth Strings 1"],
  [56, "Trumpet"],
  [57, "Trombone"],
  [59, "Muted Trumpet"],
  [60, "French Horn"],
  [65, "Alto Sax"],
  [66, "Tenor Sax"],
  [71, "Clarinet"],
  [73, "Flute"],
  [75, "Pan Flute"],
  [79, "Ocarina"],
  [82, "Lead 3 (calliope, usually resembling a woodwind)"],
  [83, "Lead 4 (chiff)"],
  [
    88,
    "Pad 1 (new age, pad stacked with a bell, often derived from 'Fantasia' patch from Roland D-50)",
  ],
  [98, "FX (crystal, a synthesized bell sound)"],
  [100, "FX 5 (brightness, bright pad stacked with choir or bell)"],
  [101, "FX 6 (goblins, a slow-attack pad with chirping or murmuring sounds)"],
  [124, "Telephone Ring"],
  [125, "Helicopter"],
];

export const filterList = filterOut.map((entry) => entry[0]);

export const keep = [
  [0, "Acoustic Grand Piano or Piano 1"],
  [1, "Bright Acoustic Piano or Piano 2"],
  [3, "Honky-tonk Piano"],
  [4, "Electric Piano 1 (usually a Rhodes or Wurlitzer piano)"],
  [5, "Electric Piano 2 (usually an FM piano patch, often chorused)"],
  [11, "Vibraphone"],
  [12, "Marimba"],
  [16, "Drawbar Organ or Organ 1"],
  [17, "Percussive Organ or Organ 2"],
];

export const bass = [32, 33, 34, 35, 36, 37, 38, 43];

export const eventTypes = {
  channelAftertouch: false,
  controller: false,
  copyrightNotice: true,
  cuePoint: true,
  endOfTrack: true,
  keySignature: true,
  lyrics: true,
  marker: true,
  noteOff: false,
  noteOn: false,
  pitchBend: false,
  portPrefix: true,
  programChange: false,
  sequencerSpecific: true,
  setTempo: true,
  smpteOffset: true,
  sysEx: false,
  text: true,
  timeSignature: true,
  trackName: true,
};

export const metaEvents = [
  "copyrightNotice",
  "cuePoint",
  "endOfTrack",
  "keySignature",
  "lyrics",
  "marker",
  "portPrefix",
  "programChange",
  "sequencerSpecific",
  "setTempo",
  "smpteOffset",
  "sysEx",
  "text",
  "timeSignature",
  "trackName",
];

export const channelEvents = [
  "noteOn",
  "noteOff",
  "controller",
  "programChange",
  "pitchBend",
  "channelAftertouch",
];

export const nonChannelEvents = [
  "keySignature",
  "smpteOffset",
  "trackName",
  "sequencerSpecific",
  "setTempo",
  "timeSignature",
  "text",
  "endOfTrack",
  "marker",
  "copyrightNotice",
  "sysEx",
  "portPrefix",
  "lyrics",
  "cuePoint",
];
